### ISSUE TITLE
イカのマークダウン習得

### ISSUE THREAD

**Issue by hiroaki14358** [okahiro/Test#2]

**Comment by hiroaki14358** [comment]
### いまアスタでリストを使えるようになった。
- ほら！
  - ほらっ！

**Comment by hiroaki14358** [comment]
## チェックリストを作れるらしい
- [ ] チェックリスト1
- [x] チェックリスト2

**Comment by hiroaki14358** [comment]
## 太字ができるらしい

えーと、**ここ**を太字にしてくれい！

**Comment by hiroaki14358** [comment]
## 斜体もできる

*で囲むだけ

_ほらね_

**Comment by hiroaki14358** [comment]
## コード部分はバッククォートで挟む

バッククォートは shift+@ で出る

`int a = 23;`

**Comment by hiroaki14358** [comment]
## リンクを貼る

[Google](https://www.google.co.jp/)

https://www.google.co.jp/
こういう風に直接はってもいいけど、長いurlの時とかに便利かもね。

**Comment by hiroaki14358** [comment]
## 引用はあたまに>をつける

> 引用だよーん。
> かしこまった文章。かしこまった文章。

一行空ければ引用は終了するんだね。

#### issue内で以前の発言を引用する時とかに使うらしい。

**Comment by hiroaki14358** [comment]
## コミットIDもリンク作れるだと！？

98e47add31114494e88fed32f001e1e237b46f20

あ、ほんとだ。

**Comment by hiroaki14358** [comment]
## 色付きでコードを貼れるだと！？

``` C++
int a = 23;

for (int i=0; i<10; i++) {
//なにかやる
}

```

**Comment by hiroaki14358** [comment]
とりあえず基本は押さえました。大丈夫でしょう。

**Comment by okahiro** [comment]
Awesome!

**Comment by hiroaki14358** [comment]
:smile:

**Comment by hiroaki14358** [comment]
失ったらもったいないので、自分のマインドマップにまとめました。なのでリポジトリ消しちゃっても大丈夫。
